add_newline = true

format = """
[ î‚¶](fg:bright-cyan)$username[ï‘„](bg:bright-cyan fg:black)$hostname[î‚´](fg:bright-cyan) \
[î‚¶](fg:bright-blue)$directory[î‚´](fg:bright-blue) \
 $character
"""

right_format = """
$git_branch$git_status\
$direnv$docker_context\
$lua$nix_shell$rust$golang$nodejs$deno$python$dart$c\
$cmake\
[î‚¶](fg:green)$cmd_duration[î‚´](fg:green)
"""

[username]
disabled = false
show_always = true
format = "[$user ]($style)"
style_user = "fg:black bg:bright-cyan"
style_root = "fg:red bg:bright-cyan"

[hostname]
disabled = false
ssh_only = false
ssh_symbol = "ïˆ"
format = "[ $hostname]($style)"
style = "fg:black bg:bright-cyan"
trim_at = "."

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)[ ï ]($repo_root_style)"
read_only_style = "fg:black bg:red"
repo_root_style = "fg:black bg:bright-blue"
style = "fg:black bg:bright-blue"
truncation_symbol = "â‹¯"
use_os_path_sep = true
truncation_length = 2
read_only = " â—ˆ"

[directory.substitutions]
"~/Documents" = "ó°ˆ™ "
"~/Downloads" = "ï€™ "
"~/Pictures" = "ï€¾ "
"~/.config" = "ï€“ "
"~/Videos" = "ï€½ "
"~/Music" = "ï€ "
"~/Dev" = "ó°…´ "

[fill]
symbol = " "

[cmd_duration]
format = '[ï€— $duration]($style)'
style = "fg:black bg:green"
show_milliseconds = true
min_time = 0

[character]
success_symbol = "[ğŸˆ](fg:green bold)"
error_symbol = "[ğŸˆ](fr:red bold)"
vicmd_symbol = "[ğŸˆ](fg:yellow bold)"
